/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TutoresRouteImport } from './routes/tutores'
import { Route as SalvosRouteImport } from './routes/salvos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as MaterialIdRouteImport } from './routes/material.$id'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TutoresRoute = TutoresRouteImport.update({
  id: '/tutores',
  path: '/tutores',
  getParentRoute: () => rootRouteImport,
} as any)
const SalvosRoute = SalvosRouteImport.update({
  id: '/salvos',
  path: '/salvos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialIdRoute = MaterialIdRouteImport.update({
  id: '/material/$id',
  path: '/material/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/marketplace': typeof MarketplaceRoute
  '/notificacoes': typeof NotificacoesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/salvos': typeof SalvosRoute
  '/tutores': typeof TutoresRoute
  '/upload': typeof UploadRoute
  '/material/$id': typeof MaterialIdRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/marketplace': typeof MarketplaceRoute
  '/notificacoes': typeof NotificacoesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/salvos': typeof SalvosRoute
  '/tutores': typeof TutoresRoute
  '/upload': typeof UploadRoute
  '/material/$id': typeof MaterialIdRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/marketplace': typeof MarketplaceRoute
  '/notificacoes': typeof NotificacoesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/salvos': typeof SalvosRoute
  '/tutores': typeof TutoresRoute
  '/upload': typeof UploadRoute
  '/material/$id': typeof MaterialIdRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/configuracoes'
    | '/dashboard'
    | '/marketplace'
    | '/notificacoes'
    | '/reset-password'
    | '/salvos'
    | '/tutores'
    | '/upload'
    | '/material/$id'
    | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/configuracoes'
    | '/dashboard'
    | '/marketplace'
    | '/notificacoes'
    | '/reset-password'
    | '/salvos'
    | '/tutores'
    | '/upload'
    | '/material/$id'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/configuracoes'
    | '/dashboard'
    | '/marketplace'
    | '/notificacoes'
    | '/reset-password'
    | '/salvos'
    | '/tutores'
    | '/upload'
    | '/material/$id'
    | '/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  MarketplaceRoute: typeof MarketplaceRoute
  NotificacoesRoute: typeof NotificacoesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SalvosRoute: typeof SalvosRoute
  TutoresRoute: typeof TutoresRoute
  UploadRoute: typeof UploadRoute
  MaterialIdRoute: typeof MaterialIdRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutores': {
      id: '/tutores'
      path: '/tutores'
      fullPath: '/tutores'
      preLoaderRoute: typeof TutoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salvos': {
      id: '/salvos'
      path: '/salvos'
      fullPath: '/salvos'
      preLoaderRoute: typeof SalvosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material/$id': {
      id: '/material/$id'
      path: '/material/$id'
      fullPath: '/material/$id'
      preLoaderRoute: typeof MaterialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  MarketplaceRoute: MarketplaceRoute,
  NotificacoesRoute: NotificacoesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SalvosRoute: SalvosRoute,
  TutoresRoute: TutoresRoute,
  UploadRoute: UploadRoute,
  MaterialIdRoute: MaterialIdRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
